### ISSUE TITLE
NaN should become a number

### ISSUE THREAD

**Issue by remexre** [skeeto/elisp-ffi#11]
```
(type-of (ffi-call nil "sqrt" [:double :double] -1))
symbol
```

**Comment by skeeto** [comment]
Elisp has an unusual printed representation for NaN: -0.0e+NaN. The C++
side just needs to detect NaN (i.e. isnan(3)) and print this specific
string accordingly.

**Comment by remexre** [comment]
I'm gonna add a unit test for this after lunch, then does #12 look good to merge?

**Comment by skeeto** [comment]
Yeah, this looks good to me, so I merged it. Good idea handling
infinity, too. Forgot about that. Thanks!
