### ISSUE TITLE
Please release an initial version

### ISSUE THREAD

**Issue by DamienCassou** [skeeto/elisp-ffi#8]
To facilitate packaging of your library, could you please release an initial version? Just adding a git tag is enough for me.

**Comment by skeeto** [comment]
Sure thing. I just added a package header and tagged 1.0.0.

**Comment by DamienCassou** [comment]
Thank you. The nix package manager now contains elisp-ffi https://github.com/NixOS/nixpkgs/commit/971b90e98d7cebf9d8b5a0cb48db9efd47539100
